package endecd;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

public class LayarUtama extends javax.swing.JFrame {

    private BigInteger biNilaiP;
    private BigInteger biNilaiG;
    private BigInteger biNilaiX;
    private BigInteger biNilaiY;

    private BigInteger biNilaiK;

    private BigInteger biNilaiM;
    private BigInteger biNilaiB;

    private BufferedImage biGambarEnkrip;
    private BufferedImage biGambarDekrip;
    private JFileChooser pilihanBerkas;

    private char karakter;
    private int nilai;

    public LayarUtama() {
        tampilanJendela();
        initComponents();

        setLocationRelativeTo(null);

        intFraBuatKunci.setVisible(false);
        intFraEnkripsi.setVisible(false);
        intFraDekrip.setVisible(false);
        intFraAbout.setVisible(false);
        intFraHelp.setVisible(false);
    }

    private void tampilanJendela() {
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if ("Nimbus".equals(installedLookAndFeel.getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayarUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        intFraBuatKunci = new javax.swing.JInternalFrame();
        panelBuatKunci = new javax.swing.JPanel();
        btnGenerateKunci = new javax.swing.JButton();
        btnKeluar1 = new javax.swing.JButton();
        pnlWidget = new javax.swing.JPanel();
        lblKataKunci = new javax.swing.JLabel();
        txtKataKunci = new javax.swing.JTextField();
        intFraEnkripsi = new javax.swing.JInternalFrame();
        panelEnkripsi = new javax.swing.JPanel();
        txtBrowse = new javax.swing.JTextField();
        txtCitraAsli = new javax.swing.JLabel();
        lblCitraTerenkrip = new javax.swing.JLabel();
        btnEnkrip1 = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        pnlGbrSatu = new javax.swing.JPanel();
        lblGbrAsli = new javax.swing.JLabel();
        pnlGbrDua = new javax.swing.JPanel();
        lblGbrEnkrip = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        intFraDekrip = new javax.swing.JInternalFrame();
        panelDekripsi = new javax.swing.JPanel();
        btnBrowse1 = new javax.swing.JButton();
        txtBrowse1 = new javax.swing.JTextField();
        pnlGbr = new javax.swing.JPanel();
        lblGbr = new javax.swing.JLabel();
        pnlGbr1 = new javax.swing.JPanel();
        lblGbr1 = new javax.swing.JLabel();
        lblWaktu1 = new javax.swing.JLabel();
        lblCitraTerenkrip1 = new javax.swing.JLabel();
        lblCitraTerdekrip = new javax.swing.JLabel();
        btnDekrip1 = new javax.swing.JButton();
        btnSimpan2 = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        intFraAbout = new javax.swing.JInternalFrame();
        lblNamaAplikasi = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblPembuat = new javax.swing.JLabel();
        intFraHelp = new javax.swing.JInternalFrame();
        lblBantuan = new javax.swing.JLabel();
        lblBantu = new javax.swing.JLabel();
        scrPaneGenKun = new javax.swing.JScrollPane();
        txaGenKun = new javax.swing.JTextArea();
        lblMenEnk = new javax.swing.JLabel();
        scrPaneEnk = new javax.swing.JScrollPane();
        txaEnk = new javax.swing.JTextArea();
        pnlDek = new javax.swing.JPanel();
        lblDek = new javax.swing.JLabel();
        scrPaneDek = new javax.swing.JScrollPane();
        txaDek = new javax.swing.JTextArea();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuIteKeluar = new javax.swing.JMenuItem();
        mnuTools = new javax.swing.JMenu();
        mnuIteBuaKun = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mnuIteEnkrip = new javax.swing.JMenuItem();
        mnuIteDekrip = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuIteHelp = new javax.swing.JMenuItem();
        separatorHelp = new javax.swing.JPopupMenu.Separator();
        mnuIteAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enkripsi dan Dekripsi Citra Digital");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(512, 460));
        setName("frmUtama"); // NOI18N
        setPreferredSize(new java.awt.Dimension(554, 468));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        intFraBuatKunci.setClosable(true);
        intFraBuatKunci.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFraBuatKunci.setTitle("Buat Kunci");
        intFraBuatKunci.setVisible(true);

        panelBuatKunci.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBuatKunci.setMinimumSize(new java.awt.Dimension(512, 460));

        btnGenerateKunci.setText("Generate");
        btnGenerateKunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKunciActionPerformed(evt);
            }
        });

        btnKeluar1.setText("Keluar");
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });

        pnlWidget.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKataKunci.setText("Kata Kunci");

        javax.swing.GroupLayout pnlWidgetLayout = new javax.swing.GroupLayout(pnlWidget);
        pnlWidget.setLayout(pnlWidgetLayout);
        pnlWidgetLayout.setHorizontalGroup(
            pnlWidgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWidgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKataKunci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKataKunci, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlWidgetLayout.setVerticalGroup(
            pnlWidgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWidgetLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlWidgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKataKunci)
                    .addComponent(lblKataKunci))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout panelBuatKunciLayout = new javax.swing.GroupLayout(panelBuatKunci);
        panelBuatKunci.setLayout(panelBuatKunciLayout);
        panelBuatKunciLayout.setHorizontalGroup(
            panelBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuatKunciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateKunci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlWidget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuatKunciLayout.setVerticalGroup(
            panelBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuatKunciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlWidget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBuatKunciLayout.createSequentialGroup()
                        .addComponent(btnGenerateKunci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKeluar1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout intFraBuatKunciLayout = new javax.swing.GroupLayout(intFraBuatKunci.getContentPane());
        intFraBuatKunci.getContentPane().setLayout(intFraBuatKunciLayout);
        intFraBuatKunciLayout.setHorizontalGroup(
            intFraBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuatKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        intFraBuatKunciLayout.setVerticalGroup(
            intFraBuatKunciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuatKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
        );

        intFraEnkripsi.setClosable(true);
        intFraEnkripsi.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFraEnkripsi.setTitle(" Enkripsi");
        intFraEnkripsi.setVisible(true);

        panelEnkripsi.setMinimumSize(new java.awt.Dimension(512, 460));

        txtBrowse.setEditable(false);

        txtCitraAsli.setText("Citra Asli");

        lblCitraTerenkrip.setText("Citra Terenkrip");

        btnEnkrip1.setText("Enkrip");
        btnEnkrip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnkrip1ActionPerformed(evt);
            }
        });

        btnSimpan1.setText("Simpan");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        pnlGbrSatu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlGbrSatuLayout = new javax.swing.GroupLayout(pnlGbrSatu);
        pnlGbrSatu.setLayout(pnlGbrSatuLayout);
        pnlGbrSatuLayout.setHorizontalGroup(
            pnlGbrSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGbrAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlGbrSatuLayout.setVerticalGroup(
            pnlGbrSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGbrAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlGbrDua.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlGbrDuaLayout = new javax.swing.GroupLayout(pnlGbrDua);
        pnlGbrDua.setLayout(pnlGbrDuaLayout);
        pnlGbrDuaLayout.setHorizontalGroup(
            pnlGbrDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGbrEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlGbrDuaLayout.setVerticalGroup(
            pnlGbrDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGbrEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblWaktu.setText("waktu: ");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnkripsiLayout = new javax.swing.GroupLayout(panelEnkripsi);
        panelEnkripsi.setLayout(panelEnkripsiLayout);
        panelEnkripsiLayout.setHorizontalGroup(
            panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnkripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnkripsiLayout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblWaktu))
                    .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEnkripsiLayout.createSequentialGroup()
                            .addComponent(btnEnkrip1)
                            .addGap(18, 18, 18)
                            .addComponent(btnSimpan1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKembali))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEnkripsiLayout.createSequentialGroup()
                            .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCitraAsli)
                                .addComponent(pnlGbrSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlGbrDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCitraTerenkrip)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEnkripsiLayout.setVerticalGroup(
            panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnkripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktu)
                    .addComponent(btnBrowse)
                    .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlGbrSatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGbrDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCitraAsli)
                    .addComponent(lblCitraTerenkrip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnkrip1)
                    .addComponent(btnSimpan1)
                    .addComponent(btnKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout intFraEnkripsiLayout = new javax.swing.GroupLayout(intFraEnkripsi.getContentPane());
        intFraEnkripsi.getContentPane().setLayout(intFraEnkripsiLayout);
        intFraEnkripsiLayout.setHorizontalGroup(
            intFraEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        intFraEnkripsiLayout.setVerticalGroup(
            intFraEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        intFraDekrip.setClosable(true);
        intFraDekrip.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFraDekrip.setTitle("Dekripsi");
        intFraDekrip.setVisible(true);

        panelDekripsi.setMinimumSize(new java.awt.Dimension(512, 460));

        btnBrowse1.setText("Browse");
        btnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse1ActionPerformed(evt);
            }
        });

        txtBrowse1.setEditable(false);

        pnlGbr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlGbrLayout = new javax.swing.GroupLayout(pnlGbr);
        pnlGbr.setLayout(pnlGbrLayout);
        pnlGbrLayout.setHorizontalGroup(
            pnlGbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGbrLayout.createSequentialGroup()
                .addComponent(lblGbr, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlGbrLayout.setVerticalGroup(
            pnlGbrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGbrLayout.createSequentialGroup()
                .addComponent(lblGbr, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGbr1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlGbr1Layout = new javax.swing.GroupLayout(pnlGbr1);
        pnlGbr1.setLayout(pnlGbr1Layout);
        pnlGbr1Layout.setHorizontalGroup(
            pnlGbr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGbr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlGbr1Layout.setVerticalGroup(
            pnlGbr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGbr1Layout.createSequentialGroup()
                .addComponent(lblGbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblWaktu1.setText("waktu: ");

        lblCitraTerenkrip1.setText("Citra Terenkrip");

        lblCitraTerdekrip.setText("Citra Terdekrip");

        btnDekrip1.setText("Dekrip");
        btnDekrip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDekrip1ActionPerformed(evt);
            }
        });

        btnSimpan2.setText("Simpan");
        btnSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan2ActionPerformed(evt);
            }
        });

        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDekripsiLayout = new javax.swing.GroupLayout(panelDekripsi);
        panelDekripsi.setLayout(panelDekripsiLayout);
        panelDekripsiLayout.setHorizontalGroup(
            panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDekripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDekripsiLayout.createSequentialGroup()
                        .addComponent(btnBrowse1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblWaktu1))
                    .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelDekripsiLayout.createSequentialGroup()
                            .addComponent(btnDekrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSimpan2)
                            .addGap(43, 43, 43)
                            .addComponent(btnKembali1))
                        .addGroup(panelDekripsiLayout.createSequentialGroup()
                            .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCitraTerenkrip1)
                                .addComponent(pnlGbr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlGbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCitraTerdekrip)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDekripsiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlGbr, pnlGbr1});

        panelDekripsiLayout.setVerticalGroup(
            panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDekripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse1)
                    .addComponent(txtBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWaktu1))
                .addGap(18, 18, 18)
                .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGbr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlGbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitraTerenkrip1)
                    .addComponent(lblCitraTerdekrip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDekrip1)
                    .addComponent(btnKembali1)
                    .addComponent(btnSimpan2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDekripsiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlGbr, pnlGbr1});

        javax.swing.GroupLayout intFraDekripLayout = new javax.swing.GroupLayout(intFraDekrip.getContentPane());
        intFraDekrip.getContentPane().setLayout(intFraDekripLayout);
        intFraDekripLayout.setHorizontalGroup(
            intFraDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        intFraDekripLayout.setVerticalGroup(
            intFraDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        intFraAbout.setClosable(true);
        intFraAbout.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFraAbout.setTitle("About");
        intFraAbout.setVisible(true);

        lblNamaAplikasi.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        lblNamaAplikasi.setText("Enkripsi dan Dekripsi");

        lblNama.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNama.setText("Citra Digital");

        lblPembuat.setText("Dibuat oleh Surti April Astuti");

        javax.swing.GroupLayout intFraAboutLayout = new javax.swing.GroupLayout(intFraAbout.getContentPane());
        intFraAbout.getContentPane().setLayout(intFraAboutLayout);
        intFraAboutLayout.setHorizontalGroup(
            intFraAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intFraAboutLayout.createSequentialGroup()
                .addGroup(intFraAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intFraAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaAplikasi))
                    .addGroup(intFraAboutLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(intFraAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPembuat)
                            .addComponent(lblNama))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        intFraAboutLayout.setVerticalGroup(
            intFraAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intFraAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPembuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        intFraHelp.setClosable(true);
        intFraHelp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFraHelp.setTitle("Help");
        intFraHelp.setVisible(true);

        lblBantuan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblBantuan.setText("Bantuan Aplikasi");

        lblBantu.setText("Menu Generate Kunci");

        txaGenKun.setEditable(false);
        txaGenKun.setColumns(20);
        txaGenKun.setLineWrap(true);
        txaGenKun.setRows(5);
        txaGenKun.setText("Untuk melakukan generate kunci \nAnda harus menginputkan kata kunci dan kemudian tekan tombol generate ");
        txaGenKun.setWrapStyleWord(true);
        txaGenKun.setEnabled(false);
        scrPaneGenKun.setViewportView(txaGenKun);

        lblMenEnk.setText("Menu Enkrip");

        txaEnk.setEditable(false);
        txaEnk.setColumns(20);
        txaEnk.setRows(5);
        txaEnk.setText("Anda harus melakukan browse untuk\nmencari file citra yang akan di \nenkrip, setelah gambar tertampil\nklik tombol enkrip, maka gambar\ntersebut akan ke enkrip. Anda\nbisa menyimpan atau kembali\nke menu utama. ");
        txaEnk.setAutoscrolls(false);
        txaEnk.setEnabled(false);
        scrPaneEnk.setViewportView(txaEnk);

        lblDek.setText("Menu Dekrip");

        txaDek.setEditable(false);
        txaDek.setColumns(20);
        txaDek.setRows(5);
        txaDek.setText("Klik tombol browse untuk  mencari\nfile citra yang akan didekrip. \nSetelah gambar tampil lalu klik\ntombol dekrip untuk mengembali\nkan file citra seperti gambar\nsemula. Anda bisa menyimpan\natau kembali ke menu utama.");
        txaDek.setAutoscrolls(false);
        txaDek.setEnabled(false);
        scrPaneDek.setViewportView(txaDek);

        javax.swing.GroupLayout pnlDekLayout = new javax.swing.GroupLayout(pnlDek);
        pnlDek.setLayout(pnlDekLayout);
        pnlDekLayout.setHorizontalGroup(
            pnlDekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDek)
            .addComponent(scrPaneDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlDekLayout.setVerticalGroup(
            pnlDekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDekLayout.createSequentialGroup()
                .addComponent(lblDek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPaneDek, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout intFraHelpLayout = new javax.swing.GroupLayout(intFraHelp.getContentPane());
        intFraHelp.getContentPane().setLayout(intFraHelpLayout);
        intFraHelpLayout.setHorizontalGroup(
            intFraHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intFraHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intFraHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBantuan)
                    .addGroup(intFraHelpLayout.createSequentialGroup()
                        .addGroup(intFraHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMenEnk)
                            .addComponent(scrPaneEnk, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(lblBantu)
                            .addComponent(scrPaneGenKun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        intFraHelpLayout.setVerticalGroup(
            intFraHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intFraHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBantuan)
                .addGap(18, 18, 18)
                .addGroup(intFraHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intFraHelpLayout.createSequentialGroup()
                        .addComponent(lblBantu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPaneGenKun, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMenEnk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPaneEnk, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(pnlDek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(intFraBuatKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(173, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intFraEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(intFraDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(intFraAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(intFraHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(intFraBuatKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intFraEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(intFraDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(intFraAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(intFraHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        desktop.setLayer(intFraBuatKunci, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(intFraEnkripsi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(intFraDekrip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(intFraAbout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(intFraHelp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(desktop);

        mnuBar.setFocusable(false);

        mnuFile.setText("File");

        mnuIteKeluar.setText("Keluar");
        mnuIteKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuIteKeluar);

        mnuBar.add(mnuFile);

        mnuTools.setText("Tools");

        mnuIteBuaKun.setText("Buat Kunci");
        mnuIteBuaKun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteBuaKunActionPerformed(evt);
            }
        });
        mnuTools.add(mnuIteBuaKun);
        mnuTools.add(separator);

        mnuIteEnkrip.setText("Enkripsi");
        mnuIteEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteEnkripActionPerformed(evt);
            }
        });
        mnuTools.add(mnuIteEnkrip);

        mnuIteDekrip.setText("Dekripsi");
        mnuIteDekrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteDekripActionPerformed(evt);
            }
        });
        mnuTools.add(mnuIteDekrip);

        mnuBar.add(mnuTools);

        mnuHelp.setText("Help");

        mnuIteHelp.setText("Help ");
        mnuIteHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteHelpActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIteHelp);
        mnuHelp.add(separatorHelp);

        mnuIteAbout.setText("About");
        mnuIteAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIteAbout);

        mnuBar.add(mnuHelp);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        try {
            pilihanBerkas = new JFileChooser();
            pilihanBerkas.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "bmp"));
            int buka = pilihanBerkas.showOpenDialog(this);
            if (buka == JFileChooser.APPROVE_OPTION) {
                String gambar = pilihanBerkas.getSelectedFile().getAbsolutePath();
                txtBrowse.setText(gambar);
                lblGbrAsli.setIcon(new ImageIcon(gambar));
                lblGbrEnkrip.setIcon(new ImageIcon(gambar));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        intFraEnkripsi.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        intFraBuatKunci.setVisible(false);
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    private void btnGenerateKunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateKunciActionPerformed
        
        
        try {
            StringBuilder sbTeksKunci = new StringBuilder();
            String kataKunci = txtKataKunci.getText();
            for (int i = 0; i < kataKunci.length(); i++) {
                karakter = kataKunci.charAt(i);
                nilai = (int) karakter;
                sbTeksKunci.append(nilai);
            }
            
            SecureRandom srNilaiAcak = SecureRandom.getInstance("SHA1PRNG");
            srNilaiAcak.getAlgorithm();
            srNilaiAcak.setSeed(sbTeksKunci.toString().getBytes());
            
            // int nilaiPAcak = srNilaiAcak.nextInt(257) + 15;
            BigInteger nilaiPAcak = BigInteger.probablePrime(8, srNilaiAcak);
            int nilaiGAcak = srNilaiAcak.nextInt(nilaiPAcak.intValue() - 1) + 2;
            /*while ((nilaiGAcak > nilaiPAcak)) {
                nilaiGAcak = srNilaiAcak.nextInt(nilaiPAcak - 1) + 2;
            }*/
            
            int nilaiXAcak = srNilaiAcak.nextInt(nilaiPAcak.intValue() - 2) + 2;
            /*while ((nilaiXAcak > nilaiPAcak)) {
                nilaiXAcak = srNilaiAcak.nextInt(nilaiPAcak - 2) + 2;
            }*/
            
            int nilaiKAcak = srNilaiAcak.nextInt(nilaiPAcak.intValue() - 3) + 17;
          
            /*while ((!isPrime(nilaiPAcak)) && (nilaiPAcak < 255)) {
                nilaiPAcak = srNilaiAcak.nextInt(257);
            }*/
            
            // biNilaiP = new BigInteger(Integer.toString(nilaiPAcak));
            biNilaiP = new BigInteger(nilaiPAcak.toString());
            System.out.println("Nilai p acak: " + biNilaiP.toString());
            biNilaiG = new BigInteger(Integer.toString(nilaiGAcak));
            System.out.println("Nilai g acak: " + biNilaiG.toString());
            biNilaiX = new BigInteger(Integer.toString(nilaiXAcak));
            System.out.println("Nilai x acak: " + biNilaiX.toString());
            biNilaiY = biNilaiG.modPow(biNilaiX, biNilaiP);
            System.out.println("Nilai y acak: " + biNilaiY.toString());
            biNilaiK = new BigInteger(Integer.toString(nilaiKAcak));
            System.out.println("Nilai k acak: " + biNilaiK.toString());
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + ex.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LayarUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateKunciActionPerformed

    private static boolean isPrime(int inputNum){
        if (inputNum <= 3 || inputNum % 2 == 0) {
            return inputNum == 2 || inputNum == 3; 
        }
        
        int divisor = 3;
        while ((divisor <= Math.sqrt(inputNum)) && (inputNum % divisor != 0)) {
            divisor += 2; 
        }
        
        return inputNum % divisor != 0; 
    }
    
    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        intFraDekrip.setVisible(false);
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan2ActionPerformed
        try {
            JFileChooser pilBerkas = new JFileChooser();
            pilBerkas.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "bmp"));

            int simpan = pilBerkas.showSaveDialog(this);
            if (simpan == JFileChooser.APPROVE_OPTION) {

                File fBerkasSimpan = pilBerkas.getSelectedFile();

                ImageIO.write(biGambarDekrip, "PNG", fBerkasSimpan);
                JOptionPane.showMessageDialog(this, "Berkas berhasil disimpan", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpan2ActionPerformed

    private void btnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse1ActionPerformed
        try {
            pilihanBerkas = new JFileChooser();
            pilihanBerkas.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "bmp"));
            int buka = pilihanBerkas.showOpenDialog(this);

            if (buka == JFileChooser.APPROVE_OPTION) {
                String gambar = pilihanBerkas.getSelectedFile().getAbsolutePath();
                txtBrowse1.setText(gambar);
                lblGbr1.setIcon(new ImageIcon(gambar));
                lblGbr.setIcon(new ImageIcon(gambar));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBrowse1ActionPerformed

    private void btnDekrip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDekrip1ActionPerformed
        try {
            File fBerkas = new File(txtBrowse1.getText());
            BufferedImage biGambar = ImageIO.read(fBerkas);
            biGambarDekrip = new BufferedImage(biGambar.getWidth(), biGambar.getHeight(), BufferedImage.TYPE_INT_RGB);
            System.out.println("Dimensi gambar " + biGambar.getWidth() + "x" + biGambar.getHeight() + " pixel");

            long waktuMulai = System.currentTimeMillis();
            for (int x = 0; x < biGambar.getWidth(); x++) {
                for (int y = 0; y < biGambar.getHeight(); y++) {
                    Color warna = new Color(biGambar.getRGB(x, y));
                    int merah = warna.getRed();
                    int hijau = warna.getGreen();
                    int biru = warna.getBlue();

                    int merahDekrip = this.dekrip(merah);
                    if (merahDekrip > 255) {
                        merahDekrip = 255;
                    }

                    int hijauDekrip = this.dekrip(hijau);
                    if (hijauDekrip > 255) {
                        hijauDekrip = 255;
                    }

                    int biruDekrip = this.dekrip(biru);
                    if (biruDekrip > 255) {
                        biruDekrip = 255;
                    }

                    Color warnaJadi = new Color(merahDekrip, hijauDekrip, biruDekrip);
                    biGambarDekrip.setRGB(x, y, warnaJadi.getRGB());
                }
            }

            lblGbr.setIcon(new ImageIcon(biGambarDekrip));
            long waktuSelesai = (System.currentTimeMillis() - waktuMulai);
            System.out.println("Proses enkripsi selesai, " + waktuSelesai + " detik");
            lblWaktu1.setText("waktu: " + waktuSelesai + " detik");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDekrip1ActionPerformed

    private int dekrip(int warnaRGB) {
        // Rumus dekripsi dari ElGamal
        BigInteger a = biNilaiG.modPow(biNilaiK, biNilaiP);
        BigInteger b = new BigInteger(Integer.toString(warnaRGB));
        BigInteger m = b.multiply(a.pow(biNilaiP.intValue() - 1 - biNilaiX.intValue())).mod(biNilaiP);
        return m.intValue();
    }

    private void btnEnkrip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnkrip1ActionPerformed
        try {
            File fBerkas = new File(txtBrowse.getText());
            BufferedImage biGambar = ImageIO.read(fBerkas);
            biGambarEnkrip = new BufferedImage(biGambar.getWidth(), biGambar.getHeight(), BufferedImage.TYPE_INT_RGB);
            System.out.println("Dimensi gambar " + biGambar.getWidth() + "x" + biGambar.getHeight() + " pixel");

            long waktuMulai = System.currentTimeMillis();
            for (int x = 0; x < biGambar.getWidth(); x++) {
                for (int y = 0; y < biGambar.getHeight(); y++) {
                    Color warna = new Color(biGambar.getRGB(x, y));
                    int merah = warna.getRed();
                    int hijau = warna.getGreen();
                    int biru = warna.getBlue();

                    int merahEnkrip = this.enkrip(merah);
                    if (merahEnkrip > 255) {
                        merahEnkrip = 255;
                    }

                    int hijauEnkrip = this.enkrip(hijau);
                    if (hijauEnkrip > 255) {
                        hijauEnkrip = 255;
                    }

                    int biruEnkrip = this.enkrip(biru);
                    if (biruEnkrip > 255) {
                        biruEnkrip = 255;
                    }

                    Color warnaJadi = new Color(merahEnkrip, hijauEnkrip, biruEnkrip);

                    biGambarEnkrip.setRGB(x, y, warnaJadi.getRGB());
                }
            }

            lblGbrEnkrip.setIcon(new ImageIcon(biGambarEnkrip));
            long waktuSelesai = (System.currentTimeMillis() - waktuMulai);
            System.out.println("Proses enkripsi selesai, " + waktuSelesai + " detik");
            lblWaktu.setText("waktu: " + waktuSelesai + " detik");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnkrip1ActionPerformed

    private int enkrip(int warnaRGB) {
        // Rumus enkripsi dari ElGamal
        biNilaiM = new BigInteger(Integer.toString(warnaRGB));
        biNilaiB = biNilaiY.pow(biNilaiK.intValue()).multiply(biNilaiM).mod(biNilaiP);
        return biNilaiB.intValue();
    }

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        try {
            JFileChooser pilBerkas = new JFileChooser();
            pilBerkas.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "bmp"));

            int simpan = pilBerkas.showSaveDialog(this);
            if (simpan == JFileChooser.APPROVE_OPTION) {
                File fBerkasSimpan = pilBerkas.getSelectedFile();
                ImageIO.write(biGambarEnkrip, "PNG", fBerkasSimpan);
                JOptionPane.showMessageDialog(this, "Berkas berhasil disimpan", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan!\n" + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void mnuIteKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuIteKeluarActionPerformed

    private void mnuIteBuaKunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteBuaKunActionPerformed
        try {
            intFraBuatKunci.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan " + e.getMessage(), "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuIteBuaKunActionPerformed

    private void mnuIteEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteEnkripActionPerformed
        try {
            intFraEnkripsi.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan " + e.getMessage(), "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuIteEnkripActionPerformed

    private void mnuIteDekripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteDekripActionPerformed
        try {
            intFraDekrip.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan " + e.getMessage(), "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_mnuIteDekripActionPerformed

    private void mnuIteAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteAboutActionPerformed
        intFraAbout.setVisible(true);
    }//GEN-LAST:event_mnuIteAboutActionPerformed

    private void mnuIteHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteHelpActionPerformed
        intFraHelp.setVisible(true);
    }//GEN-LAST:event_mnuIteHelpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBrowse1;
    private javax.swing.JButton btnDekrip1;
    private javax.swing.JButton btnEnkrip1;
    private javax.swing.JButton btnGenerateKunci;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnSimpan2;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JInternalFrame intFraAbout;
    private javax.swing.JInternalFrame intFraBuatKunci;
    private javax.swing.JInternalFrame intFraDekrip;
    private javax.swing.JInternalFrame intFraEnkripsi;
    private javax.swing.JInternalFrame intFraHelp;
    private javax.swing.JLabel lblBantu;
    private javax.swing.JLabel lblBantuan;
    private javax.swing.JLabel lblCitraTerdekrip;
    private javax.swing.JLabel lblCitraTerenkrip;
    private javax.swing.JLabel lblCitraTerenkrip1;
    private javax.swing.JLabel lblDek;
    private javax.swing.JLabel lblGbr;
    private javax.swing.JLabel lblGbr1;
    private javax.swing.JLabel lblGbrAsli;
    private javax.swing.JLabel lblGbrEnkrip;
    private javax.swing.JLabel lblKataKunci;
    private javax.swing.JLabel lblMenEnk;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaAplikasi;
    private javax.swing.JLabel lblPembuat;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JLabel lblWaktu1;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuIteAbout;
    private javax.swing.JMenuItem mnuIteBuaKun;
    private javax.swing.JMenuItem mnuIteDekrip;
    private javax.swing.JMenuItem mnuIteEnkrip;
    private javax.swing.JMenuItem mnuIteHelp;
    private javax.swing.JMenuItem mnuIteKeluar;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JPanel panelBuatKunci;
    private javax.swing.JPanel panelDekripsi;
    private javax.swing.JPanel panelEnkripsi;
    private javax.swing.JPanel pnlDek;
    private javax.swing.JPanel pnlGbr;
    private javax.swing.JPanel pnlGbr1;
    private javax.swing.JPanel pnlGbrDua;
    private javax.swing.JPanel pnlGbrSatu;
    private javax.swing.JPanel pnlWidget;
    private javax.swing.JScrollPane scrPaneDek;
    private javax.swing.JScrollPane scrPaneEnk;
    private javax.swing.JScrollPane scrPaneGenKun;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JPopupMenu.Separator separatorHelp;
    private javax.swing.JTextArea txaDek;
    private javax.swing.JTextArea txaEnk;
    private javax.swing.JTextArea txaGenKun;
    private javax.swing.JTextField txtBrowse;
    private javax.swing.JTextField txtBrowse1;
    private javax.swing.JLabel txtCitraAsli;
    private javax.swing.JTextField txtKataKunci;
    // End of variables declaration//GEN-END:variables

}
